- hosts: "{{project}}"
  gather_facts: true
  vars:
    backup_to: "{{deploy_to}}_{{branch}}_{{ansible_date_time.epoch}}"
    site_url: "http://www.showerlee.com"
  roles:
    - deploy
      

     #- debug:
     #    msg="{{backup_to}}"
